receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:5555

processors:
  batch:
    timeout: 5s
    send_batch_size: 1024

extensions:
  health_check:
  pprof:
    endpoint: 0.0.0.0:6666
    
exporters:
  awsxray:
    region: 'us-east-1'

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [awsxray]
  extensions: [health_check]
  telemetry:
    logs:
      level: debug      
