receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:5555

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024

extensions:
  health_check:
  pprof:
    endpoint: 0.0.0.0:6666
    
exporters:
  prometheus:
    endpoint: collector:7777
    namespace: default
  otlp:
    endpoint: tempo:4317
    tls:
      insecure: true

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
  extensions: [health_check]
  telemetry:
    logs:
      level: debug
